### ISSUE TITLE
how to query on SPARKSQL

### ISSUE THREAD

**Issue by heenasalim** [BenFradet/struct-type-encoder#41]
Hi Team,

I am trying following SQL:-

var work__store_level_vend_pack_loc_final_data =

  sparksession.read.format("csv")
 .option("header", "true")
 .option("delimiter", "|")
 .option("inferSchema", "true")
 .load("C:\\Users\\jabin\\Desktop\\project_files\\work__store_level_vend_pack_loc_final_data.txt");
 
  work__store_level_vend_pack_loc_final_data.registerTempTable("work__store_level_vend_pack_loc_final_data_table");

var r1 = sparksession.sqlContext.sql( "SELECT shc_item_id ,'K' as source_owner_cd,item_purchase_status_cd, vendor_package_id,vendor_package_purchase_status_cd,flow_type_cd as vendor_package_flow_type_cd,vendor_carton_qty,vendor_stock_nbr,ksn_package_id,ksn_purchase_status_cd,import_ind,sears_divission_nbr,sears_item_nbr,sears_sku_nbr,scan_based_trading_ind,cross_merchandising_cd,retail_carton_vendor_package_id,vendor_package_owner_cd,can_carry_model_id,'' AS days_to_check_begin_day_qty,'' AS days_to_check_end_day_qty ,dotcom_allocation_ind ,retail_carton_internal_package_qty,allocation_replenishment_cd,shc_item_type_cd,idrp_order_method_cd,source_package_qty as store_source_package_qty,order_duns_nbr FROM work__store_level_vend_pack_loc_final_data_table WHERE flow_type_cd = 'JIT' OR servicing_dc_nbr > '0' ")
// .collect.foreach(println)

now i want to distinct all column of the r1 using sparksession.sqlContext.sql("")
how to do above thing?

**Comment by BenFradet** [comment]
hello, it's not clear to me where you're using the library?

**Comment by heenasalim** [comment]
I am using common libraries in pom.xml
import org.apache.spark.sql._
import org.apache.spark.sql.Row
import org.apache.spark.sql.functions
import org.apache.spark.sql.types;
import org.apache.spark.sql.SparkSession

**Comment by heenasalim** [comment]
package Heena

import org.apache.spark.SparkContext

import org.apache.spark.sql._
import org.apache.spark.sql.Row
import org.apache.spark.sql.functions
import org.apache.spark.sql.types;
import org.apache.spark.sql.SparkSession


object vendor {
  
  def main(args:Array[String])
  {
    
   //Reading the files in dataframe forms
   //The spark.read.csv function is dataframe 
   //when we pass case class/type to this data frame like sparkread.csv.as[Person]/csv.as[String]
   //it becomes dataset  which can be handle exacty as method 1 project1 ie select and filter
    
     val sparksession = SparkSession.builder().master("local").
     appName("kmart_vendor_pakage_location").getOrCreate();
     import sparksession.implicits._
    
     var gold__item_aprk_current_data
     = sparksession.read.format("csv")
     .option("header","true")
     .option("delimiter","|")
     .option("inferSchema","true")
     .load("C:\\Users\\jabin\\Desktop\\project_files\\gold_item_aprk_current_data.txt")
         
    var work__store_level_vend_pack_loc_final_data =
      
      sparksession.read.format("csv")
     .option("header", "true")
     .option("delimiter", "|")
     .option("inferSchema", "true")
     .load("C:\\Users\\jabin\\Desktop\\project_files\\work__store_level_vend_pack_loc_final_data.txt");
     
      work__store_level_vend_pack_loc_final_data.registerTempTable("work__store_level_vend_pack_loc_final_data_table");
     
    var r1 = sparksession.sqlContext.sql( "SELECT shc_item_id ,'K' as source_owner_cd,item_purchase_status_cd, vendor_package_id,vendor_package_purchase_status_cd,flow_type_cd as vendor_package_flow_type_cd,vendor_carton_qty,vendor_stock_nbr,ksn_package_id,ksn_purchase_status_cd,import_ind,sears_divission_nbr,sears_item_nbr,sears_sku_nbr,scan_based_trading_ind,cross_merchandising_cd,retail_carton_vendor_package_id,vendor_package_owner_cd,can_carry_model_id,'' AS days_to_check_begin_day_qty,'' AS days_to_check_end_day_qty ,dotcom_allocation_ind ,retail_carton_internal_package_qty,allocation_replenishment_cd,shc_item_type_cd,idrp_order_method_cd,source_package_qty as store_source_package_qty,order_duns_nbr FROM work__store_level_vend_pack_loc_final_data_table WHERE flow_type_cd = 'JIT'  OR servicing_dc_nbr > '0' ")
     // }}

The whole spark scala code.

My problem is I want to select distinct columns from r1 , for that I am using following
      sparksession.sqlContext.sql("select distinct * from work__store_level_vend_pack_loc_final_data_table")
.collect.foreach(println);
but it showing result on original table not on latest r1.

**Comment by heenasalim** [comment]
@BenFradet 
[work__store_level_vend_pack_loc_final_data.txt](https://github.com/BenFradet/struct-type-encoder/files/3013863/work__store_level_vend_pack_loc_final_data.txt)


> input files are attached.

**Comment by BenFradet** [comment]
Hello, it doesn't seem that you use this library, I would suggest reaching out to the spark community as a whole: https://spark.apache.org/community.html

**Comment by heenasalim** [comment]
What s relation between spark community and github?

there is noneed of the tag apache-spark as no any tag field is there in
Github.

**Comment by BenFradet** [comment]
if you're looking for the spark github repo it's there: https://github.com/apache/spark
